/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics */
        get: operations["get_analytics_api_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cover-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Cover Letters */
        post: operations["launch_cover_letters_api_cover_letters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cover-letters/{cover_letter_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Cover Letter Pdf */
        get: operations["download_cover_letter_pdf_api_cover_letters__cover_letter_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cover-letters/{cover_letter_id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Cover Letter Endpoint */
        post: operations["revise_cover_letter_endpoint_api_cover_letters__cover_letter_id__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Discover */
        post: operations["launch_discover_api_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gmail/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Gmail Sync */
        post: operations["launch_gmail_sync_api_gmail_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manual Job */
        post: operations["create_manual_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Jobs */
        post: operations["bulk_jobs_api_jobs_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/from-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Add From Url */
        post: operations["launch_add_from_url_api_jobs_from_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Detail */
        get: operations["get_job_detail_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job Endpoint */
        delete: operations["delete_job_endpoint_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /** Patch Job */
        patch: operations["patch_job_api_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Application */
        put: operations["upsert_application_api_jobs__job_id__application_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/select-cover-letter/{cover_letter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Cover Letter Endpoint */
        post: operations["select_cover_letter_endpoint_api_jobs__job_id__select_cover_letter__cover_letter_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/select-resume/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Resume Endpoint */
        post: operations["select_resume_endpoint_api_jobs__job_id__select_resume__version_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match-gap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match Gap */
        get: operations["get_match_gap_api_match_gap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match-gap/refresh-clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Match Gap Clusters */
        post: operations["refresh_match_gap_clusters_api_match_gap_refresh_clusters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_notifications__notification_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss */
        post: operations["dismiss_api_notifications__notification_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pipeline */
        get: operations["get_pipeline_api_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prune */
        post: operations["prune_api_prune_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Pull */
        post: operations["launch_pull_api_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Refresh */
        post: operations["launch_refresh_api_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Reprocess */
        post: operations["launch_reprocess_api_reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume-versions/{version_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Pdf */
        get: operations["download_pdf_api_resume_versions__version_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume-versions/{version_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Endpoint */
        post: operations["render_endpoint_api_resume_versions__version_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume-versions/{version_id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Endpoint */
        post: operations["revise_endpoint_api_resume_versions__version_id__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Request cooperative cancellation. The worker stops at its next progress
         *     checkpoint; the run then settles into the ``cancelled`` terminal state.
         */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shortlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shortlist */
        get: operations["get_shortlist_api_shortlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources Route */
        get: operations["list_sources_route_api_sources_get"];
        put?: never;
        /** Add Source Route */
        post: operations["add_source_route_api_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Source Route */
        post: operations["preview_source_route_api_sources_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Source Route */
        delete: operations["remove_source_route_api_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Set Enabled Route */
        patch: operations["set_enabled_route_api_sources__source_id__patch"];
        trace?: never;
    };
    "/api/suggestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Suggestion Runs */
        post: operations["launch_suggestion_runs_api_suggestion_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggestion */
        get: operations["get_suggestion_api_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggestions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Generate */
        post: operations["launch_generate_api_suggestions_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Tailor */
        post: operations["launch_tailor_api_tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Triage */
        get: operations["get_triage_api_triage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddJobTextRequest */
        AddJobTextRequest: {
            /** Company */
            company?: string | null;
            /** Jdtext */
            jdText: string;
            /** Location */
            location?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** AddJobUrlParams */
        AddJobUrlParams: {
            /**
             * Allowbrowser
             * @default true
             */
            allowBrowser: boolean;
            /** Company */
            company?: string | null;
            /** Location */
            location?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** AddSourceIn */
        AddSourceIn: {
            /** Label */
            label?: string | null;
            /** Url */
            url: string;
        };
        /** AnalyticsOut */
        AnalyticsOut: {
            /** Byband */
            byBand: components["schemas"]["CohortOut"][];
            /** Bysource */
            bySource: components["schemas"]["CohortOut"][];
        };
        /** ApplicationOut */
        ApplicationOut: {
            /** Coverletterid */
            coverLetterId?: number | null;
            /** Id */
            id: number;
            /** Jobid */
            jobId: number;
            /** Notes */
            notes: string | null;
            /** Resumeversionid */
            resumeVersionId?: number | null;
            /** Status */
            status: string;
            /** Submittedat */
            submittedAt: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ApplicationUpsert */
        ApplicationUpsert: {
            /** Notes */
            notes?: string | null;
            /** Status */
            status: string;
        };
        /** BoardPage[PipelineItem] */
        BoardPage_PipelineItem_: {
            /** Data */
            data: components["schemas"]["PipelineItem"][];
            /** Facets */
            facets: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            pagination: components["schemas"]["Pagination"];
            /** Total */
            total: number;
        };
        /** BoardPage[ShortlistItem] */
        BoardPage_ShortlistItem_: {
            /** Data */
            data: components["schemas"]["ShortlistItem"][];
            /** Facets */
            facets: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            pagination: components["schemas"]["Pagination"];
            /** Total */
            total: number;
        };
        /** BoardPage[TriageItem] */
        BoardPage_TriageItem_: {
            /** Data */
            data: components["schemas"]["TriageItem"][];
            /** Facets */
            facets: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            pagination: components["schemas"]["Pagination"];
            /** Total */
            total: number;
        };
        /** BulkRequest */
        BulkRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "archive" | "restore" | "delete" | "approve" | "setStatus";
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Board
             * @enum {string}
             */
            board: "shortlist" | "triage" | "pipeline";
            /** City */
            city?: string[];
            /** Companysize */
            companySize?: string[];
            /** Country */
            country?: string[];
            /**
             * Dryrun
             * @default true
             */
            dryRun: boolean;
            /** Employmenttype */
            employmentType?: string[];
            /** Ids */
            ids?: number[];
            /** Industry */
            industry?: string[];
            /** Maxfit */
            maxFit?: number | null;
            /** Minfit */
            minFit?: number | null;
            /** Minsalary */
            minSalary?: number | null;
            /**
             * Preset
             * @default balanced
             */
            preset: string;
            /** Q */
            q?: string | null;
            /** Region */
            region?: string[];
            /** Remote */
            remote?: string[];
            /**
             * Scope
             * @enum {string}
             */
            scope: "ids" | "query";
            /** Seniority */
            seniority?: string[];
            /** Skills */
            skills?: string[];
            /**
             * Sortby
             * @default fit
             */
            sortBy: string;
            /** Source */
            source?: string[];
            /** Sponsorship */
            sponsorship?: string[];
            /** Staledays */
            staleDays?: number | null;
            /** Status */
            status?: string | null;
            /** Statusin */
            statusIn?: string[];
        };
        /** BulkResultOut */
        BulkResultOut: {
            /** Affected */
            affected: number;
            /** Reasons */
            reasons: {
                [key: string]: number;
            };
            /** Skipped */
            skipped: number;
        };
        /** CohortOut */
        CohortOut: {
            /** Applications */
            applications: number;
            /** Interviewrate */
            interviewRate: number;
            /** Interviews */
            interviews: number;
            /** Label */
            label: string;
            /** Offerrate */
            offerRate: number;
            /** Offers */
            offers: number;
            /** Responserate */
            responseRate: number;
            /** Responses */
            responses: number;
        };
        /** CoverLetterOut */
        CoverLetterOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Factcheckpassed */
            factCheckPassed: boolean;
            /** Id */
            id: number;
            /** Instruction */
            instruction?: string | null;
            /** Jobid */
            jobId: number;
            /**
             * Origin
             * @default draft
             */
            origin: string;
            /** Parentid */
            parentId?: number | null;
            /** Pdfpath */
            pdfPath: string | null;
            /** Resumeversionid */
            resumeVersionId?: number | null;
        };
        /** CoverLetterParams */
        CoverLetterParams: {
            /**
             * Approved
             * @default false
             */
            approved: boolean;
            /** Jobids */
            jobIds?: number[] | null;
        };
        /** DemandEdgeOut */
        DemandEdgeOut: {
            /** Jobid */
            jobId: number;
            /** Skill */
            skill: string;
            /** Skillkey */
            skillKey: string;
            /**
             * Source
             * @enum {string}
             */
            source: "must" | "nice" | "tech";
        };
        /** DiscoverParams */
        DiscoverParams: Record<string, never>;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetail */
        JobDetail: {
            application: components["schemas"]["ApplicationOut"] | null;
            /** Archivedat */
            archivedAt: string | null;
            /** Company */
            company: string | null;
            /** Companysize */
            companySize?: string | null;
            /**
             * Coverletters
             * @default []
             */
            coverLetters: components["schemas"]["CoverLetterOut"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Criteriajson */
            criteriaJson: {
                [key: string]: unknown;
            } | null;
            /** Employmenttype */
            employmentType?: string | null;
            /** Fitrationale */
            fitRationale: string | null;
            /** Fitscore */
            fitScore: number | null;
            /** Hasprogress */
            hasProgress: boolean;
            /** Id */
            id: number;
            /** Industry */
            industry?: string | null;
            /** Jdtext */
            jdText: string;
            /** Location */
            location: string | null;
            /** Locationcity */
            locationCity?: string | null;
            /** Locationcountry */
            locationCountry?: string | null;
            /** Locationregion */
            locationRegion?: string | null;
            /** Postedat */
            postedAt: string | null;
            /** Remotepolicy */
            remotePolicy?: string | null;
            /** Resumeversions */
            resumeVersions: components["schemas"]["ResumeVersionOut"][];
            /** Salarycurrency */
            salaryCurrency?: string | null;
            /** Salarymax */
            salaryMax?: number | null;
            /** Salarymin */
            salaryMin?: number | null;
            /** Seniority */
            seniority?: string | null;
            /** Sicdivision */
            sicDivision?: string | null;
            /** Siclabel */
            sicLabel?: string | null;
            /** Sicmajor */
            sicMajor?: string | null;
            /** Skills */
            skills: components["schemas"]["SkillTagOut"][];
            /** Source */
            source: string;
            /** Sponsorshipsignal */
            sponsorshipSignal?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string | null;
        };
        /** JobLiteOut */
        JobLiteOut: {
            /** Company */
            company?: string | null;
            /** Id */
            id: number;
            /** Seniority */
            seniority?: string | null;
            /** Title */
            title?: string | null;
        };
        /** JobPatch */
        JobPatch: {
            /** Archived */
            archived?: boolean | null;
            /** Status */
            status?: string | null;
        };
        /** MatchGapOut */
        MatchGapOut: {
            /** Clustersstale */
            clustersStale: boolean;
            /** Edges */
            edges: components["schemas"]["DemandEdgeOut"][];
            /** Jobs */
            jobs: components["schemas"]["JobLiteOut"][];
            /** Skills */
            skills: components["schemas"]["SkillNodeOut"][];
            /** Suggestionstatuses */
            suggestionStatuses?: components["schemas"]["SuggestionStatusOut"][];
            /** Targettotal */
            targetTotal: number;
            /** Themes */
            themes: components["schemas"]["ThemeOut"][];
        };
        /** NotificationOut */
        NotificationOut: {
            /** Applicationid */
            applicationId: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Evidence */
            evidence: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Messageid */
            messageId: string;
            /** Proposedstatus */
            proposedStatus: string;
            /** State */
            state: string;
        };
        /** Page[RunOut] */
        Page_RunOut_: {
            /** Data */
            data: components["schemas"]["RunOut"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** Pagination */
        Pagination: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalitems */
            totalItems: number;
            /** Totalpages */
            totalPages: number;
        };
        /** PipelineItem */
        PipelineItem: {
            /** Applicationstatus */
            applicationStatus: string | null;
            /** Company */
            company: string | null;
            /** Critiquejson */
            critiqueJson: {
                [key: string]: unknown;
            }[] | null;
            /** Fitscore */
            fitScore: number | null;
            /** Hasprogress */
            hasProgress: boolean;
            /** Jdtext */
            jdText: string;
            /** Jobid */
            jobId: number;
            /** Pdfpath */
            pdfPath: string | null;
            /** Remotepolicy */
            remotePolicy: string | null;
            /** Salarymax */
            salaryMax: number | null;
            /** Salarymin */
            salaryMin: number | null;
            /** Seniority */
            seniority: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Skillsdemonstrated */
            skillsDemonstrated: string[];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** PruneOverrides */
        PruneOverrides: {
            /**
             * Dryrun
             * @default true
             */
            dryRun: boolean;
            /** Fitthreshold */
            fitThreshold?: number | null;
            /** Retentiondays */
            retentionDays?: number | null;
            /** Staledays */
            staleDays?: number | null;
        };
        /** PruneReportOut */
        PruneReportOut: {
            /** Archived */
            archived: number;
            /** Expired */
            expired: number;
            /** Lowfit */
            lowFit: number;
            /** Rejected */
            rejected: number;
            /** Skipped */
            skipped: number;
            /** Stale */
            stale: number;
        };
        /** PullParams */
        PullParams: {
            /** Limit */
            limit?: number | null;
            /** Sourceids */
            sourceIds?: string[] | null;
        };
        /** RefreshParams */
        RefreshParams: {
            /** Limit */
            limit?: number | null;
        };
        /** RepoOut */
        RepoOut: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Stars */
            stars?: number | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Why */
            why: string;
        };
        /** ReprocessParams */
        ReprocessParams: {
            /** Scopes */
            scopes?: string[];
        };
        /** ResourceOut */
        ResourceOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "doc" | "tutorial";
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** ResumeVersionOut */
        ResumeVersionOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Critiquejson */
            critiqueJson: {
                [key: string]: unknown;
            }[] | null;
            /** Factcheckpassed */
            factCheckPassed: boolean;
            /** Id */
            id: number;
            /** Instruction */
            instruction?: string | null;
            /** Jobid */
            jobId: number;
            /**
             * Origin
             * @default tailor
             */
            origin: string;
            /** Parentversionid */
            parentVersionId?: number | null;
            /** Pdfpath */
            pdfPath: string | null;
            /** Reviewscore */
            reviewScore: number | null;
            /** Round */
            round: number;
        };
        /** ReviseRequest */
        ReviseRequest: {
            /** Instruction */
            instruction: string;
            /**
             * Rereview
             * @default false
             */
            reReview: boolean;
        };
        /** RunOut */
        RunOut: {
            /** Current */
            current: number;
            /** Error */
            error?: string | null;
            /** Etatext */
            etaText?: string | null;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Percent */
            percent: number;
            /** Result */
            result?: unknown | null;
            /** Runid */
            runId: string;
            state: components["schemas"]["RunState"];
            /** Total */
            total: number;
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "pending" | "running" | "cancelling" | "done" | "error" | "cancelled";
        /** SetEnabledIn */
        SetEnabledIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** ShortlistItem */
        ShortlistItem: {
            /** Company */
            company: string | null;
            /** Companysize */
            companySize: string | null;
            /** Employmenttype */
            employmentType: string | null;
            /** Fitrationale */
            fitRationale: string | null;
            /** Fitscore */
            fitScore: number | null;
            /** Industry */
            industry: string | null;
            /** Jobid */
            jobId: number;
            /** Location */
            location: string | null;
            /** Locationcity */
            locationCity?: string | null;
            /** Locationcountry */
            locationCountry?: string | null;
            /** Locationregion */
            locationRegion?: string | null;
            /** Postedat */
            postedAt: string | null;
            /** Remotepolicy */
            remotePolicy: string | null;
            /** Salarycurrency */
            salaryCurrency: string | null;
            /** Salarymax */
            salaryMax: number | null;
            /** Salarymin */
            salaryMin: number | null;
            /** Seniority */
            seniority: string | null;
            /** Sicdivision */
            sicDivision?: string | null;
            /** Siclabel */
            sicLabel?: string | null;
            /** Sicmajor */
            sicMajor?: string | null;
            /** Skills */
            skills: components["schemas"]["SkillTagOut"][];
            /** Sponsorshipsignal */
            sponsorshipSignal: string | null;
            /** Title */
            title: string | null;
        };
        /** SkillNodeOut */
        SkillNodeOut: {
            /** Covered */
            covered: boolean;
            /** Jobcount */
            jobCount: number;
            /** Key */
            key: string;
            /** Members */
            members: {
                [key: string]: number;
            };
            /** Must */
            must: number;
            /** Nice */
            nice: number;
            /** Skill */
            skill: string;
            /** Tech */
            tech: number;
            /** Themeid */
            themeId?: string | null;
        };
        /** SkillTagOut */
        SkillTagOut: {
            /** Covered */
            covered: boolean;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /** SourceOut */
        SourceOut: {
            /** Detail */
            detail: string;
            /** Displayname */
            displayName: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Pullable */
            pullable: boolean;
            /** Type */
            type: string;
        };
        /** SourcePreviewIn */
        SourcePreviewIn: {
            /** Label */
            label?: string | null;
            /** Url */
            url: string;
        };
        /** SourcePreviewOut */
        SourcePreviewOut: {
            /** Error */
            error?: string | null;
            /** Kind */
            kind?: string | null;
            /** Label */
            label?: string | null;
            /** Ok */
            ok: boolean;
            /** Rolecount */
            roleCount?: number | null;
            /** Token */
            token?: string | null;
            /** Url */
            url: string;
        };
        /** SuggestionEnvelope */
        SuggestionEnvelope: {
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            suggestion?: components["schemas"]["SuggestionOut"] | null;
        };
        /** SuggestionOut */
        SuggestionOut: {
            /** Bridge */
            bridge: string;
            /** Citations */
            citations: string[];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "skill" | "theme";
            project?: components["schemas"]["ProjectOut"] | null;
            /** Repos */
            repos: components["schemas"]["RepoOut"][];
            /** Resources */
            resources: components["schemas"]["ResourceOut"][];
        };
        /** SuggestionRunAcceptedOut */
        SuggestionRunAcceptedOut: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "skill" | "theme";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "accepted";
            /** Runid */
            runId: string;
        };
        /** SuggestionRunNotFoundOut */
        SuggestionRunNotFoundOut: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "skill" | "theme";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "not_found";
        };
        /** SuggestionRunsOut */
        SuggestionRunsOut: {
            /** Results */
            results: (components["schemas"]["SuggestionRunAcceptedOut"] | components["schemas"]["SuggestionRunNotFoundOut"])[];
        };
        /** SuggestionRunsRequest */
        SuggestionRunsRequest: {
            /** Targets */
            targets: components["schemas"]["SuggestionTarget"][];
        };
        /** SuggestionStatusOut */
        SuggestionStatusOut: {
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "skill" | "theme";
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "stale";
        };
        /** SuggestionTarget */
        SuggestionTarget: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "skill" | "theme";
        };
        /** TailorParams */
        TailorParams: {
            /**
             * Approved
             * @default false
             */
            approved: boolean;
            /** Jobids */
            jobIds?: number[] | null;
        };
        /** ThemeOut */
        ThemeOut: {
            /** Essentialscore */
            essentialScore: number;
            /** Gapcount */
            gapCount: number;
            /** Id */
            id: string;
            /** Jobcount */
            jobCount: number;
            /** Label */
            label: string;
            /** Popularscore */
            popularScore: number;
            /** Skillcount */
            skillCount: number;
        };
        /** TriageItem */
        TriageItem: {
            /** Archivedat */
            archivedAt: string | null;
            /** Company */
            company: string | null;
            /** Fitscore */
            fitScore: number | null;
            /** Hasprogress */
            hasProgress: boolean;
            /** Jobid */
            jobId: number;
            /** Location */
            location: string | null;
            /** Postedat */
            postedAt: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_analytics_api_analytics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_cover_letters_api_cover_letters_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverLetterParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_cover_letter_pdf_api_cover_letters__cover_letter_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cover_letter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_cover_letter_endpoint_api_cover_letters__cover_letter_id__revise_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cover_letter_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverLetterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_discover_api_discover_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DiscoverParams"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_gmail_sync_api_gmail_sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_manual_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddJobTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_jobs_api_jobs_bulk_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_add_from_url_api_jobs_from_url_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddJobUrlParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_detail_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_endpoint_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_job_api_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_application_api_jobs__job_id__application_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_cover_letter_endpoint_api_jobs__job_id__select_cover_letter__cover_letter_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
                cover_letter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_resume_endpoint_api_jobs__job_id__select_resume__version_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_gap_api_match_gap_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchGapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_match_gap_clusters_api_match_gap_refresh_clusters_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_api_notifications__notification_id__accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_api_notifications__notification_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_api_pipeline_get: {
        parameters: {
            query?: {
                source?: string | null;
                status?: string | null;
                remote?: string | null;
                sponsorship?: string | null;
                seniority?: string | null;
                employmentType?: string | null;
                industry?: string | null;
                country?: string | null;
                region?: string | null;
                city?: string | null;
                companySize?: string | null;
                skills?: string | null;
                minFit?: number | null;
                maxFit?: number | null;
                minSalary?: number | null;
                staleDays?: number | null;
                q?: string | null;
                sortBy?: string;
                page?: number;
                pageSize?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPage_PipelineItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prune_api_prune_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PruneOverrides"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PruneReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_pull_api_pull_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PullParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_refresh_api_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshParams"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_reprocess_api_reprocess_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReprocessParams"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_pdf_api_resume_versions__version_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_endpoint_api_resume_versions__version_id__render_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_endpoint_api_resume_versions__version_id__revise_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shortlist_api_shortlist_get: {
        parameters: {
            query?: {
                q?: string | null;
                source?: string | null;
                status?: string | null;
                remote?: string | null;
                sponsorship?: string | null;
                seniority?: string | null;
                employmentType?: string | null;
                industry?: string | null;
                country?: string | null;
                region?: string | null;
                city?: string | null;
                companySize?: string | null;
                skills?: string | null;
                minFit?: number | null;
                maxFit?: number | null;
                minSalary?: number | null;
                staleDays?: number | null;
                sortBy?: string;
                page?: number;
                pageSize?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPage_ShortlistItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_route_api_sources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_source_route_api_sources_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSourceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_source_route_api_sources_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_source_route_api_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_enabled_route_api_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEnabledIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_suggestion_runs_api_suggestion_runs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionRunsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionRunsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suggestion_api_suggestions_get: {
        parameters: {
            query: {
                kind: "skill" | "theme";
                key: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_generate_api_suggestions_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionTarget"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_tailor_api_tailor_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_triage_api_triage_get: {
        parameters: {
            query?: {
                archived?: boolean;
                q?: string | null;
                source?: string | null;
                status?: string | null;
                remote?: string | null;
                sponsorship?: string | null;
                seniority?: string | null;
                employmentType?: string | null;
                industry?: string | null;
                country?: string | null;
                region?: string | null;
                city?: string | null;
                companySize?: string | null;
                skills?: string | null;
                minFit?: number | null;
                maxFit?: number | null;
                minSalary?: number | null;
                staleDays?: number | null;
                sortBy?: string;
                page?: number;
                pageSize?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPage_TriageItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
