import datetime as _dt

import yaml

from resume_agent.setup.state import WizardState


def _header() -> str:
    today = _dt.date.today().isoformat()
    return f"# Generated by 'resume-agent setup' on {today} — see README for field docs\n"


def parse_greenhouse_boards(text: str) -> list[dict]:
    """One board per line: ``token`` or ``token, Company Name``."""
    boards: list[dict] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        token, _, company = stripped.partition(",")
        token = token.strip()
        if not token:
            continue
        company = company.strip() or token.title()
        boards.append({"token": token, "company": company})
    return boards
