from resume_agent.config import load_yaml
from resume_agent.discovery.connectors.config import load_connectors_config
from resume_agent.discovery.search_config import load_search_config
from resume_agent.render.render_config import load_render_config
from resume_agent.setup.state import WizardState
from resume_agent.setup.yaml_gen import (
    build_connectors,
    build_profile_sources,
    build_search,
    parse_greenhouse_boards,
    parse_list,
    render_from_example,
)
from resume_agent.tailor.review_config import load_review_config


def test_parse_list_splits_on_commas_and_newlines():
    assert parse_list("python, kafka\ngo") == ["python", "kafka", "go"]


def test_parse_list_trims_and_drops_blanks():
    assert parse_list("  python ,, \n , go \n\n") == ["python", "go"]


def test_parse_list_empty_is_empty_list():
    assert parse_list("") == []


def test_parses_token_and_company():
    boards = parse_greenhouse_boards("stripe, Stripe\nairbnb, Airbnb")
    assert boards == [
        {"token": "stripe", "company": "Stripe"},
        {"token": "airbnb", "company": "Airbnb"},
    ]


def test_token_only_defaults_company_to_titlecased_token():
    assert parse_greenhouse_boards("datadog") == [{"token": "datadog", "company": "Datadog"}]


def test_skips_blank_lines_and_trims():
    assert parse_greenhouse_boards("\n  stripe ,  Stripe \n\n") == [
        {"token": "stripe", "company": "Stripe"}
    ]


def test_empty_input_is_empty_list():
    assert parse_greenhouse_boards("") == []


# ── Task 4 ──────────────────────────────────────────────────────────────────
def test_build_profile_sources_round_trips(tmp_path):
    state = WizardState(resume_path="resume.pdf", github_username="octocat")
    text = build_profile_sources(state)
    assert text.startswith("# Generated by 'resume-agent setup'")
    p = tmp_path / "profile_sources.yaml"
    p.write_text(text, encoding="utf-8")
    data = load_yaml(p)
    assert data["resume_path"] == "resume.pdf"
    assert data["github_username"] == "octocat"


# ── Task 5 ──────────────────────────────────────────────────────────────────
def test_build_search_round_trips(tmp_path):
    state = WizardState(
        keywords=["python"], titles=["Backend Engineer"], locations=["Remote"],
        remote_policy="remote", min_salary=120000, yoe_min=0, yoe_max=5,
        sponsorship_required=True,
    )
    p = tmp_path / "search.yaml"
    p.write_text(build_search(state), encoding="utf-8")
    cfg = load_search_config(p)
    assert cfg.keywords == ["python"]
    assert cfg.min_salary == 120000
    assert cfg.sponsorship_required is True
    assert cfg.remote_policy == "remote"


# ── Task 6 ──────────────────────────────────────────────────────────────────
def test_build_connectors_round_trips(tmp_path):
    state = WizardState(
        greenhouse_enabled=True,
        greenhouse_boards=[{"token": "stripe", "company": "Stripe"}],
        adzuna_enabled=True, adzuna_country="gb",
        remoteok_enabled=True, linkedin_enabled=False,
    )
    p = tmp_path / "connectors.yaml"
    p.write_text(build_connectors(state), encoding="utf-8")
    cfg = load_connectors_config(p)
    assert cfg.greenhouse.enabled is True
    assert cfg.greenhouse.boards[0].token == "stripe"
    assert cfg.greenhouse.boards[0].company == "Stripe"
    assert cfg.adzuna.country == "gb"
    assert cfg.remoteok.enabled is True
    assert cfg.linkedin.enabled is False


# ── Task 7 ──────────────────────────────────────────────────────────────────
def test_render_from_example_review_round_trips(tmp_path):
    text = render_from_example("config/review.yaml.example")
    assert text.startswith("# Generated by 'resume-agent setup'")
    p = tmp_path / "review.yaml"
    p.write_text(text, encoding="utf-8")
    cfg = load_review_config(p)
    assert [r.name for r in cfg.reviewers] == [
        "fact-check", "ats-keyword", "recruiter", "hiring-manager", "concision"
    ]
    assert cfg.max_rounds == 3


def test_render_from_example_render_round_trips(tmp_path):
    p = tmp_path / "render.yaml"
    p.write_text(render_from_example("config/render.yaml.example"), encoding="utf-8")
    cfg = load_render_config(p)
    assert cfg.template_path == "templates/resume.typ"
    assert cfg.output_dir == "output"
