export const SUMMARY = {
  statusCounts: {
    raw: 3,
    extracted: 1,
    filtered: 2,
    rejected: 1,
    shortlisted: 4,
    approved: 1,
    tailored: 2,
    rendered: 1,
  },
  queues: { triage: 2, approve: 4, tailor: 1, apply: 1 },
  applied: 5,
  openErrorCount: 0,
  activeInterviews: [],
  activeCoachSession: null,
  upcomingEvents: [],
  practiceStats: {
    completedSessions: 3,
    scoredSessions: 2,
    averageScore: 3.8,
    latestScore: 4.2,
    changeFromFirst: 0.8,
  },
  sourceHealth: {
    openFailures: 0,
    affectedSources: [],
    latestFailureAt: null,
  },
};
