"""ISO 3166-1 country vocabulary for `taxonomy/location.py`.

Split out of `location.py` so the parsing logic there stays readable: this
module is data, not behaviour.

`_ISO3166_NAME_TO_ISO2` is generated from the ISO 3166-1 standard (official
short names, plus an ASCII-folded variant of every accented name so
"Turkiye"/"Curacao"/"Reunion" resolve as typed). Do not hand-edit it — regenerate
it. `_parse_location` matches the longest trailing country suffix, including
official names containing commas. `COUNTRY_ALIASES` is the only half meant to
grow by hand.
"""

_ISO3166_NAME_TO_ISO2: dict[str, str] = {
    'andorra': 'AD',
    'united arab emirates': 'AE',
    'afghanistan': 'AF',
    'antigua and barbuda': 'AG',
    'anguilla': 'AI',
    'albania': 'AL',
    'armenia': 'AM',
    'angola': 'AO',
    'antarctica': 'AQ',
    'argentina': 'AR',
    'american samoa': 'AS',
    'austria': 'AT',
    'australia': 'AU',
    'aruba': 'AW',
    'aland islands': 'AX',
    'åland islands': 'AX',
    'azerbaijan': 'AZ',
    'bosnia and herzegovina': 'BA',
    'barbados': 'BB',
    'bangladesh': 'BD',
    'belgium': 'BE',
    'burkina faso': 'BF',
    'bulgaria': 'BG',
    'bahrain': 'BH',
    'burundi': 'BI',
    'benin': 'BJ',
    'saint barthelemy': 'BL',
    'saint barthélemy': 'BL',
    'bermuda': 'BM',
    'brunei darussalam': 'BN',
    'bolivia, plurinational state of': 'BO',
    'bonaire, sint eustatius and saba': 'BQ',
    'brazil': 'BR',
    'bahamas': 'BS',
    'bhutan': 'BT',
    'bouvet island': 'BV',
    'botswana': 'BW',
    'belarus': 'BY',
    'belize': 'BZ',
    'canada': 'CA',
    'cocos (keeling) islands': 'CC',
    'congo, democratic republic of the': 'CD',
    'central african republic': 'CF',
    'congo': 'CG',
    'switzerland': 'CH',
    "cote d'ivoire": 'CI',
    "côte d'ivoire": 'CI',
    'cook islands': 'CK',
    'chile': 'CL',
    'cameroon': 'CM',
    'china': 'CN',
    'colombia': 'CO',
    'costa rica': 'CR',
    'cuba': 'CU',
    'cabo verde': 'CV',
    'curacao': 'CW',
    'curaçao': 'CW',
    'christmas island': 'CX',
    'cyprus': 'CY',
    'czechia': 'CZ',
    'germany': 'DE',
    'djibouti': 'DJ',
    'denmark': 'DK',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'algeria': 'DZ',
    'ecuador': 'EC',
    'estonia': 'EE',
    'egypt': 'EG',
    'western sahara': 'EH',
    'eritrea': 'ER',
    'spain': 'ES',
    'ethiopia': 'ET',
    'finland': 'FI',
    'fiji': 'FJ',
    'falkland islands (malvinas)': 'FK',
    'micronesia, federated states of': 'FM',
    'faroe islands': 'FO',
    'france': 'FR',
    'gabon': 'GA',
    'united kingdom of great britain and northern ireland': 'GB',
    'grenada': 'GD',
    'georgia': 'GE',
    'french guiana': 'GF',
    'guernsey': 'GG',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'greenland': 'GL',
    'gambia': 'GM',
    'guinea': 'GN',
    'guadeloupe': 'GP',
    'equatorial guinea': 'GQ',
    'greece': 'GR',
    'south georgia and the south sandwich islands': 'GS',
    'guatemala': 'GT',
    'guam': 'GU',
    'guinea-bissau': 'GW',
    'guyana': 'GY',
    'hong kong': 'HK',
    'heard island and mcdonald islands': 'HM',
    'honduras': 'HN',
    'croatia': 'HR',
    'haiti': 'HT',
    'hungary': 'HU',
    'indonesia': 'ID',
    'ireland': 'IE',
    'israel': 'IL',
    'isle of man': 'IM',
    'india': 'IN',
    'british indian ocean territory': 'IO',
    'iraq': 'IQ',
    'iran, islamic republic of': 'IR',
    'iceland': 'IS',
    'italy': 'IT',
    'jersey': 'JE',
    'jamaica': 'JM',
    'jordan': 'JO',
    'japan': 'JP',
    'kenya': 'KE',
    'kyrgyzstan': 'KG',
    'cambodia': 'KH',
    'kiribati': 'KI',
    'comoros': 'KM',
    'saint kitts and nevis': 'KN',
    "korea, democratic people's republic of": 'KP',
    'korea, republic of': 'KR',
    'kuwait': 'KW',
    'cayman islands': 'KY',
    'kazakhstan': 'KZ',
    "lao people's democratic republic": 'LA',
    'lebanon': 'LB',
    'saint lucia': 'LC',
    'liechtenstein': 'LI',
    'sri lanka': 'LK',
    'liberia': 'LR',
    'lesotho': 'LS',
    'lithuania': 'LT',
    'luxembourg': 'LU',
    'latvia': 'LV',
    'libya': 'LY',
    'morocco': 'MA',
    'monaco': 'MC',
    'moldova, republic of': 'MD',
    'montenegro': 'ME',
    'saint martin (french part)': 'MF',
    'madagascar': 'MG',
    'marshall islands': 'MH',
    'north macedonia': 'MK',
    'mali': 'ML',
    'myanmar': 'MM',
    'mongolia': 'MN',
    'macao': 'MO',
    'northern mariana islands': 'MP',
    'martinique': 'MQ',
    'mauritania': 'MR',
    'montserrat': 'MS',
    'malta': 'MT',
    'mauritius': 'MU',
    'maldives': 'MV',
    'malawi': 'MW',
    'mexico': 'MX',
    'malaysia': 'MY',
    'mozambique': 'MZ',
    'namibia': 'NA',
    'new caledonia': 'NC',
    'niger': 'NE',
    'norfolk island': 'NF',
    'nigeria': 'NG',
    'nicaragua': 'NI',
    'netherlands, kingdom of the': 'NL',
    'norway': 'NO',
    'nepal': 'NP',
    'nauru': 'NR',
    'niue': 'NU',
    'new zealand': 'NZ',
    'oman': 'OM',
    'panama': 'PA',
    'peru': 'PE',
    'french polynesia': 'PF',
    'papua new guinea': 'PG',
    'philippines': 'PH',
    'pakistan': 'PK',
    'poland': 'PL',
    'saint pierre and miquelon': 'PM',
    'pitcairn': 'PN',
    'puerto rico': 'PR',
    'palestine, state of': 'PS',
    'portugal': 'PT',
    'palau': 'PW',
    'paraguay': 'PY',
    'qatar': 'QA',
    'reunion': 'RE',
    'réunion': 'RE',
    'romania': 'RO',
    'serbia': 'RS',
    'russian federation': 'RU',
    'rwanda': 'RW',
    'saudi arabia': 'SA',
    'solomon islands': 'SB',
    'seychelles': 'SC',
    'sudan': 'SD',
    'sweden': 'SE',
    'singapore': 'SG',
    'saint helena, ascension and tristan da cunha': 'SH',
    'slovenia': 'SI',
    'svalbard and jan mayen': 'SJ',
    'slovakia': 'SK',
    'sierra leone': 'SL',
    'san marino': 'SM',
    'senegal': 'SN',
    'somalia': 'SO',
    'suriname': 'SR',
    'south sudan': 'SS',
    'sao tome and principe': 'ST',
    'el salvador': 'SV',
    'sint maarten (dutch part)': 'SX',
    'syrian arab republic': 'SY',
    'eswatini': 'SZ',
    'turks and caicos islands': 'TC',
    'chad': 'TD',
    'french southern territories': 'TF',
    'togo': 'TG',
    'thailand': 'TH',
    'tajikistan': 'TJ',
    'tokelau': 'TK',
    'timor-leste': 'TL',
    'turkmenistan': 'TM',
    'tunisia': 'TN',
    'tonga': 'TO',
    'turkiye': 'TR',
    'türkiye': 'TR',
    'trinidad and tobago': 'TT',
    'tuvalu': 'TV',
    'taiwan, province of china': 'TW',
    'tanzania, united republic of': 'TZ',
    'ukraine': 'UA',
    'uganda': 'UG',
    'united states minor outlying islands': 'UM',
    'united states of america': 'US',
    'uruguay': 'UY',
    'uzbekistan': 'UZ',
    'holy see': 'VA',
    'saint vincent and the grenadines': 'VC',
    'venezuela, bolivarian republic of': 'VE',
    'virgin islands (british)': 'VG',
    'virgin islands (u.s.)': 'VI',
    'viet nam': 'VN',
    'vanuatu': 'VU',
    'wallis and futuna': 'WF',
    'samoa': 'WS',
    'yemen': 'YE',
    'mayotte': 'YT',
    'south africa': 'ZA',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
}

# Colloquial, historical and abbreviated names the standard does not carry.
# Every comma-containing official name needs an entry here to be reachable at
# all; the rest are simply what job postings actually write.
COUNTRY_ALIASES: dict[str, str] = {
    "us": "US", "usa": "US", "u.s.": "US", "u.s.a.": "US",
    "united states": "US", "united states of america": "US", "america": "US",
    "uk": "GB", "u.k.": "GB", "united kingdom": "GB", "great britain": "GB",
    "britain": "GB", "england": "GB", "scotland": "GB", "wales": "GB",
    "northern ireland": "GB",
    "uae": "AE", "united arab emirates": "AE",
    "south korea": "KR", "korea": "KR", "republic of korea": "KR",
    "north korea": "KP",
    "taiwan": "TW", "czech republic": "CZ", "czech": "CZ",
    "netherlands": "NL", "holland": "NL", "the netherlands": "NL",
    "russia": "RU", "turkey": "TR", "vietnam": "VN", "laos": "LA",
    "iran": "IR", "syria": "SY", "bolivia": "BO", "venezuela": "VE",
    "tanzania": "TZ", "moldova": "MD", "palestine": "PS", "micronesia": "FM",
    "brunei": "BN", "cape verde": "CV", "ivory coast": "CI",
    "east timor": "TL", "burma": "MM", "swaziland": "SZ", "macau": "MO",
    "vatican city": "VA", "vatican": "VA",
    "democratic republic of the congo": "CD", "dr congo": "CD", "drc": "CD",
    "republic of the congo": "CG",
}

# The full lookup: aliases win, so a curated colloquial name is never shadowed
# by an official one that happens to fold to the same key.
COUNTRY_TO_ISO2: dict[str, str] = {**_ISO3166_NAME_TO_ISO2, **COUNTRY_ALIASES}

ISO2_CODES: frozenset[str] = frozenset(COUNTRY_TO_ISO2.values())
