// SIC major-group code → display label. Generated from the backend source of
// truth at src/resume_agent/taxonomy/data/sic_codes.json (US SIC 2-digit major
// groups — a fixed government taxonomy). The board's industry facet is keyed by
// `sic_major` code (falling back to free-text `industry`), so the UI resolves
// codes to names here while still filtering/removing on the raw code.

export const SIC_LABELS: Record<string, string> = {
  "01": "Agricultural Production Crops",
  "02": "Agricultural Production Livestock",
  "07": "Agricultural Services",
  "08": "Forestry",
  "09": "Fishing, Hunting & Trapping",
  "10": "Metal Mining",
  "12": "Coal Mining",
  "13": "Oil & Gas Extraction",
  "14": "Mining of Nonmetallic Minerals",
  "15": "Building Construction-General Contractors",
  "16": "Heavy Construction",
  "17": "Construction-Special Trade Contractors",
  "20": "Food & Kindred Products",
  "21": "Tobacco Products",
  "22": "Textile Mill Products",
  "23": "Apparel & Other Finished Products",
  "24": "Lumber & Wood Products",
  "25": "Furniture & Fixtures",
  "26": "Paper & Allied Products",
  "27": "Printing & Publishing",
  "28": "Chemicals & Allied Products",
  "29": "Petroleum Refining",
  "30": "Rubber & Misc Plastics Products",
  "31": "Leather & Leather Products",
  "32": "Stone, Clay, Glass & Concrete Products",
  "33": "Primary Metal Industries",
  "34": "Fabricated Metal Products",
  "35": "Industrial Machinery & Computer Equipment",
  "36": "Electronic & Other Electrical Equipment",
  "37": "Transportation Equipment",
  "38": "Measuring & Controlling Instruments",
  "39": "Miscellaneous Manufacturing Industries",
  "40": "Railroad Transportation",
  "41": "Local & Interurban Passenger Transit",
  "42": "Motor Freight Transportation & Warehousing",
  "43": "United States Postal Service",
  "44": "Water Transportation",
  "45": "Transportation by Air",
  "46": "Pipelines, Except Natural Gas",
  "47": "Transportation Services",
  "48": "Communications",
  "49": "Electric, Gas & Sanitary Services",
  "50": "Wholesale Trade-Durable Goods",
  "51": "Wholesale Trade-Nondurable Goods",
  "52": "Building Materials & Garden Supplies",
  "53": "General Merchandise Stores",
  "54": "Food Stores",
  "55": "Automotive Dealers & Service Stations",
  "56": "Apparel & Accessory Stores",
  "57": "Home Furniture & Furnishings Stores",
  "58": "Eating & Drinking Places",
  "59": "Miscellaneous Retail",
  "60": "Depository Institutions",
  "61": "Non-depository Credit Institutions",
  "62": "Security & Commodity Brokers",
  "63": "Insurance Carriers",
  "64": "Insurance Agents, Brokers & Service",
  "65": "Real Estate",
  "67": "Holding & Other Investment Offices",
  "70": "Hotels & Other Lodging Places",
  "72": "Personal Services",
  "73": "Business Services",
  "75": "Automotive Repair, Services & Parking",
  "76": "Miscellaneous Repair Services",
  "78": "Motion Pictures",
  "79": "Amusement & Recreation Services",
  "80": "Health Services",
  "81": "Legal Services",
  "82": "Educational Services",
  "83": "Social Services",
  "84": "Museums & Botanical/Zoological Gardens",
  "86": "Membership Organizations",
  "87": "Engineering & Management Services",
  "88": "Private Households",
  "89": "Services-Miscellaneous",
  "91": "Executive, Legislative & General Government",
  "92": "Justice, Public Order & Safety",
  "93": "Public Finance & Taxation",
  "94": "Administration of Human Resource Programs",
  "95": "Administration of Environmental Programs",
  "96": "Administration of Economic Programs",
  "97": "National Security & International Affairs",
  "99": "Nonclassifiable Establishments",
};

/** Resolve an industry facet value: SIC code → label, else free-text passthrough. */
export function industryLabel(value: string): string {
  return SIC_LABELS[value] ?? value.replace(/_/g, " ");
}
