/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cover-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Cover Letters */
        post: operations["launch_cover_letters_api_cover_letters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Discover */
        post: operations["launch_discover_api_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manual Job */
        post: operations["create_manual_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/from-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Add From Url */
        post: operations["launch_add_from_url_api_jobs_from_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Detail */
        get: operations["get_job_detail_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job Endpoint */
        delete: operations["delete_job_endpoint_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /** Patch Job */
        patch: operations["patch_job_api_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Application */
        put: operations["upsert_application_api_jobs__job_id__application_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pipeline */
        get: operations["get_pipeline_api_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prune */
        post: operations["prune_api_prune_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Pull */
        post: operations["launch_pull_api_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume-versions/{version_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Pdf */
        get: operations["download_pdf_api_resume_versions__version_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume-versions/{version_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Endpoint */
        post: operations["render_endpoint_api_resume_versions__version_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shortlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shortlist */
        get: operations["get_shortlist_api_shortlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Tailor */
        post: operations["launch_tailor_api_tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Triage */
        get: operations["get_triage_api_triage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddJobTextRequest */
        AddJobTextRequest: {
            /** Company */
            company?: string | null;
            /** Jdtext */
            jdText: string;
            /** Location */
            location?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** AddJobUrlParams */
        AddJobUrlParams: {
            /**
             * Allowbrowser
             * @default true
             */
            allowBrowser: boolean;
            /** Company */
            company?: string | null;
            /** Location */
            location?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** ApplicationOut */
        ApplicationOut: {
            /** Id */
            id: number;
            /** Jobid */
            jobId: number;
            /** Notes */
            notes: string | null;
            /** Status */
            status: string;
            /** Submittedat */
            submittedAt: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ApplicationUpsert */
        ApplicationUpsert: {
            /** Notes */
            notes?: string | null;
            /** Status */
            status: string;
        };
        /** CoverLetterParams */
        CoverLetterParams: {
            /**
             * Approved
             * @default false
             */
            approved: boolean;
            /** Jobids */
            jobIds?: number[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetail */
        JobDetail: {
            application: components["schemas"]["ApplicationOut"] | null;
            /** Archivedat */
            archivedAt: string | null;
            /** Company */
            company: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Criteriajson */
            criteriaJson: {
                [key: string]: unknown;
            } | null;
            /** Fitrationale */
            fitRationale: string | null;
            /** Fitscore */
            fitScore: number | null;
            /** Hasprogress */
            hasProgress: boolean;
            /** Id */
            id: number;
            /** Jdtext */
            jdText: string;
            /** Location */
            location: string | null;
            /** Postedat */
            postedAt: string | null;
            /** Resumeversions */
            resumeVersions: components["schemas"]["ResumeVersionOut"][];
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string | null;
        };
        /** JobPatch */
        JobPatch: {
            /** Archived */
            archived?: boolean | null;
            /** Status */
            status?: string | null;
        };
        /** Page[PipelineItem] */
        Page_PipelineItem_: {
            /** Data */
            data: components["schemas"]["PipelineItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** Page[ShortlistItem] */
        Page_ShortlistItem_: {
            /** Data */
            data: components["schemas"]["ShortlistItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** Page[TriageItem] */
        Page_TriageItem_: {
            /** Data */
            data: components["schemas"]["TriageItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** Pagination */
        Pagination: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalitems */
            totalItems: number;
            /** Totalpages */
            totalPages: number;
        };
        /** PipelineItem */
        PipelineItem: {
            /** Applicationstatus */
            applicationStatus: string | null;
            /** Company */
            company: string | null;
            /** Critiquejson */
            critiqueJson: {
                [key: string]: unknown;
            }[] | null;
            /** Fitscore */
            fitScore: number | null;
            /** Hasprogress */
            hasProgress: boolean;
            /** Jdtext */
            jdText: string;
            /** Jobid */
            jobId: number;
            /** Pdfpath */
            pdfPath: string | null;
            /** Remotepolicy */
            remotePolicy: string | null;
            /** Salarymax */
            salaryMax: number | null;
            /** Salarymin */
            salaryMin: number | null;
            /** Seniority */
            seniority: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
        };
        /** PruneOverrides */
        PruneOverrides: {
            /**
             * Dryrun
             * @default true
             */
            dryRun: boolean;
            /** Fitthreshold */
            fitThreshold?: number | null;
            /** Retentiondays */
            retentionDays?: number | null;
            /** Staledays */
            staleDays?: number | null;
        };
        /** PruneReportOut */
        PruneReportOut: {
            /** Archived */
            archived: number;
            /** Expired */
            expired: number;
            /** Lowfit */
            lowFit: number;
            /** Rejected */
            rejected: number;
            /** Skipped */
            skipped: number;
            /** Stale */
            stale: number;
        };
        /** PullParams */
        PullParams: {
            /** Limit */
            limit?: number | null;
        };
        /** ResumeVersionOut */
        ResumeVersionOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Critiquejson */
            critiqueJson: {
                [key: string]: unknown;
            }[] | null;
            /** Factcheckpassed */
            factCheckPassed: boolean;
            /** Id */
            id: number;
            /** Jobid */
            jobId: number;
            /** Pdfpath */
            pdfPath: string | null;
            /** Reviewscore */
            reviewScore: number | null;
            /** Round */
            round: number;
        };
        /** RunOut */
        RunOut: {
            /** Current */
            current: number;
            /** Error */
            error?: string | null;
            /** Etatext */
            etaText?: string | null;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Percent */
            percent: number;
            /** Result */
            result?: unknown | null;
            /** Runid */
            runId: string;
            /** State */
            state: string;
            /** Total */
            total: number;
        };
        /** ShortlistItem */
        ShortlistItem: {
            /** Company */
            company: string | null;
            /** Companysize */
            companySize: string | null;
            /** Employmenttype */
            employmentType: string | null;
            /** Fitrationale */
            fitRationale: string | null;
            /** Fitscore */
            fitScore: number | null;
            /** Industry */
            industry: string | null;
            /** Jobid */
            jobId: number;
            /** Location */
            location: string | null;
            /** Postedat */
            postedAt: string | null;
            /** Remotepolicy */
            remotePolicy: string | null;
            /** Salarycurrency */
            salaryCurrency: string | null;
            /** Salarymax */
            salaryMax: number | null;
            /** Salarymin */
            salaryMin: number | null;
            /** Seniority */
            seniority: string | null;
            /** Skills */
            skills: components["schemas"]["SkillTagOut"][];
            /** Sponsorshipsignal */
            sponsorshipSignal: string | null;
            /** Title */
            title: string | null;
        };
        /** SkillTagOut */
        SkillTagOut: {
            /** Covered */
            covered: boolean;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /** TailorParams */
        TailorParams: {
            /**
             * Approved
             * @default false
             */
            approved: boolean;
            /** Jobids */
            jobIds?: number[] | null;
        };
        /** TriageItem */
        TriageItem: {
            /** Archivedat */
            archivedAt: string | null;
            /** Company */
            company: string | null;
            /** Fitscore */
            fitScore: number | null;
            /** Hasprogress */
            hasProgress: boolean;
            /** Jobid */
            jobId: number;
            /** Location */
            location: string | null;
            /** Postedat */
            postedAt: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    launch_cover_letters_api_cover_letters_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverLetterParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_discover_api_discover_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_manual_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddJobTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_add_from_url_api_jobs_from_url_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddJobUrlParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_detail_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_endpoint_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_job_api_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_application_api_jobs__job_id__application_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_api_pipeline_get: {
        parameters: {
            query?: {
                status?: string | null;
                minFit?: number | null;
                q?: string | null;
                sortBy?: string;
                page?: number;
                pageSize?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PipelineItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prune_api_prune_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PruneOverrides"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PruneReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_pull_api_pull_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PullParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_pdf_api_resume_versions__version_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_endpoint_api_resume_versions__version_id__render_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shortlist_api_shortlist_get: {
        parameters: {
            query?: {
                minFit?: number | null;
                sortBy?: string;
                page?: number;
                pageSize?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ShortlistItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_tailor_api_tailor_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_triage_api_triage_get: {
        parameters: {
            query?: {
                archived?: boolean;
                status?: string | null;
                minFit?: number | null;
                sortBy?: string;
                page?: number;
                pageSize?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TriageItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
